In [53]:
import re
file = open('sentences.txt', 'r')
tokens = {}
for i,x in enumerate (file):
    x=x.lower().strip()
    words = re.split('[^a-z]', x)
    for word in words:
        if word:
            if (not(tokens.get(word))):
                tokens.update({word:{i:1}})
            elif tokens[word].get(i):
                     tokens[word][i]+=1
            else: 
                 tokens[word].update({i:1})

In [64]:
import numpy as np
matrix = np.zeros((i+1,len(tokens)))
d=0
for column, place in iter(tokens.items()):
    for string,amount in iter(place.items()):
        matrix[string][d] = amount
    d+=1

In [74]:
distance = {}
from scipy.spatial.distance import cosine
for i in range(1,22):
    distance.update({cosine(matrix[0],matrix[i]):i})

In [88]:
output = open('output.txt','w')
sort = []
for k in sorted(distance.keys()):
    sort.append([k,distance[k]])

output.write(str(sort[0][1]))
output.write(' ')
output.write(str(sort[1][1]))
output.close()

In [96]:
def f(x): 
    return np.sin(x / 5) * np.exp(x / 10) + 5 * np.exp(-x / 2)

In [103]:
matrix = np.zeros((2,2))
matrix[0,0] = 1
matrix[0,1] =1
#matrix[0,2]=f(1)
matrix[1,0] = 1
matrix[1,1] =15
#matrix[1,2]=f(15)
b = np.array([f(1),f(15)])
b.reshape(2,1)
print(matrix)
from scipy.linalg import solve
solution = solve(matrix,b)
print(solution)

[[ 1.  1.]
 [ 1. 15.]]
[ 3.43914511 -0.18692825]


In [116]:
a = np.array([[1,1,1,1],
             [1,4,16,64],
             [1,10,100,1000],
             [1,15,225,3375]])
b = np.array([f(1),f(4),f(10),f(15)])
b.reshape(4,1)
print(a)

[[   1    1    1    1]
 [   1    4   16   64]
 [   1   10  100 1000]
 [   1   15  225 3375]]


In [117]:
solution = solve(a,b)
print(solution)

[ 4.36264154 -1.29552587  0.19333685 -0.00823565]
